config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  #Home route
  get 'home/index', as: 'home'

  #Users routes
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  post '/users', to: 'users#create'
  patch '/users/:id', to: 'users#update'

  #Sessions routes
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

  #Post routes
  get '/posts', to: 'posts#index', as: 'posts'
  get '/posts/newest', to: 'posts#date_sort', as: 'posts_by_date'
  get '/posts/:id', to: 'posts#show', as: 'post'
  get '/posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  patch '/posts/:id', to: 'posts#update'
  delete '/posts/:id', to: 'posts#destroy'

  #Topics routes
  get '/topics', to: 'topics#index', as: 'topics'
  get '/topics/:id', to: 'topics#show', as: 'topic'
  get '/topic/new', to: 'topics#new', as: 'new_topic'
  get '/topics/:id/edit', to: 'topics#edit', as: 'edit_topic'
  post '/topics', to: 'topics#create', as: 'create_topic'
  patch '/topics/:id', to: 'topics#update'
  delete '/topics/:id', to: 'topics#destroy'

  #topic-post routes
  get '/topics/:id/post/new', to: 'posts#new', as: 'new_post'
  get '/topics/:id/posts', to: 'topics#show'
  post '/topics/:id/posts', to: 'posts#create', as: 'create_post'

  # Voting routes
  resources :posts, only: [] do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end


end

app/models/classroom.rb
class Classroom < ApplicationRecord
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/index.html.erb
<div class='navbar-fixed heroImage'>
  <nav class='transparent z-depth-0'>
    <div class='nav-wrapper'>
      <div class='row'>
        <div class='col s12'>
          <a href='#' data-activates='mobile-demo' class='button-collapse show-on-large'><i class='material-icons'>menu</i></a>
          <a href='#' class='brand-logo' target='_blank'>KUMU</a>
          <ul class='right hide-on-med-and-down'>
            <li><a href='#' target='_blank'>About</a></li>
            <% if current_user %>
            <li><%= link_to "Profile", "users/#{current_user[:id]}" %></li>
            <li><%= link_to "Log Out", logout_path %></li>
          <% else %>
            <li><%= link_to "Create Account", new_user_path %></li>
            <li><%= link_to "Log In", login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <ul class='side-nav' id='mobile-demo'>
        <li>
          <a href='#' target='_blank'>About Us</a>
        </li>
        <% if current_user %>
        <li><%= link_to "Profile", users_path(current_user) %></li>
        <li><%= link_to "Log Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Create Account", new_user_path %></li>
        <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>