config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  #Home route
  get 'home/index', as: 'home'

  #Users routes
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  post '/users', to: 'users#create'
  patch '/users/:id', to: 'users#update'

  #Sessions routes
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

  #Post routes
  get '/posts', to: 'posts#index', as: 'posts'
  get '/posts/newest', to: 'posts#date_sort', as: 'posts_by_date'
  get '/posts/:id', to: 'posts#show', as: 'post'
  get '/posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  patch '/posts/:id', to: 'posts#update'
  delete '/posts/:id', to: 'posts#destroy'

  #Topics routes
  get '/topics', to: 'topics#index', as: 'topics'
  get '/topics/:id', to: 'topics#show', as: 'topic'
  get '/topic/new', to: 'topics#new', as: 'new_topic'
  get '/topics/:id/edit', to: 'topics#edit', as: 'edit_topic'
  post '/topics', to: 'topics#create', as: 'create_topic'
  patch '/topics/:id', to: 'topics#update'
  delete '/topics/:id', to: 'topics#destroy'

  #topic-post routes
  get '/topics/:id/post/new', to: 'posts#new', as: 'new_post'
  get '/topics/:id/posts', to: 'topics#show'
  post '/topics/:id/posts', to: 'posts#create', as: 'create_post'

  # Voting routes
  resources :posts, only: [] do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end


end

app/models/topic.rb
class Topic < ApplicationRecord
belongs_to :user

  #Post association Foreing keys
  has_many :posts

  #User Association Foreing Keys
  has_many :user_topics, dependent: :destroy
  has_many :users, through: :user_topics

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
    @current_user = current_user
  end

  def create
    topic = Topic.new(topic_params)
    # topic[:user_id] = current_user.id
    puts topic.inspect

    if topic.save
      redirect_to topic_path(topic)
    else
      puts topic.errors.messages
      flash[:notice]=topic.errors.messages
      render :new
    end
  end

  def show
    # use it or lose it
    topic_id = params[:id]
    @topic = Topic.find_by_id(params[:id])
    @posts = @topic.posts
    render :show
  end

  # use it or lose it
  # def edit
  #   topic_id = params[:id]
  #   @topic = Topic.find_by_id(params[:id]
  # end

  def destroy
    topic_id = params[:id]
    topic = Topic.find_by_id(topic_id)
    topic.destroy
    redirect_to topics_path
  end

def update
  @topic = Topic.find_by_id(params[:id])
  @topic.update_attributes(topic_params)
  topic.update_attributes(topic_params)
  redirect_to_topic_path(topic_id)
end

  private

  def topic_params
    params.require(:topic).permit(:name, :description)
  end

end

app/views/topics/edit.html.erb
<%= form_for @topic do |f| %>
<div class="grey lighten-4 z-depth-3">
  <div class="container">
    <h3 class="center-align">Edit Post</h3>
    <div>
      <h5>Name:</h5>
      <%= f.text_field :name %>
      <h5>Description:</h5>
      <%= f.text_field :description %>
    </div>
    <div class="center-align">
      <%= f.submit "Save Post", class:"btn-flat"%>
      <%= link_to "Cancel", topic_path(@topic.id), class:"btn-flat"%>
      <br/>
    </div>
  </div>
</div>
<% end %>

app/views/topics/index.html.erb
<h1>
  topics here
</h1>
<div class="center-align grey lighten-4">
  <div class="container grey lighten-4">
    <br/>
    <a class='dropdown-button btn-flat white grey-text text-darken-2' href='#' data-activates='dropdown1'>Filter By</a>
  </div>
  <!-- Dropdown Trigger -->
  <!-- Dropdown Structure -->

</div>
<br/>
<% @topics.each do |topic| %>
<div class="row card #fafafa hoverable">
  <div class="col s11 card-content black-text">
    <%= link_to topic.name, topic_path(topic.id)%>
  </h1>
  <h6 class="grey-text text-darken-3">
    <%= topic.description %>
  </h6>
</div>
</div>
<% end %>
<div class="center-align grey lighten-4">
<%= link_to "Home", home_path, class:"btn-flat grey-text text-darken-2"%>
</div>

app/views/topics/new.html.erb
<%= form_for :topic, url: "/topics", method: "post" do |f| %>
<div class="grey lighten-4 z-depth-3">
  <div class="container">
    <h3 class="center-align">Create New Topic</h3>
    <h5>Name:</h5>
    <%= f.text_field :name %>
    <h5>Add Description:</h5>
    <%= f.text_field :description %>
    <div class="center-align">
      <%= f.submit "Submit", class:"btn-flat"%>
      <br>
    </div>
  </div>
</div>
<% end %>

app/views/topics/show.html.erb
<div>
  <%= @topic.name %>
</div>

<div class="center-align grey lighten-4">
  <div class="container grey lighten-4">
    <br/>
    <a class='dropdown-button btn-flat white grey-text text-darken-2' href='#' data-activates='dropdown1'>Filter By</a>
  </div>
  <!-- Dropdown Trigger -->
  <!-- Dropdown Structure -->
  <ul id='dropdown1' class='dropdown-content'>
    <li>
      <a class="grey-text text-darken-2" href="#!">
        <i class="material-icons ">thumb_up</i>Votes</a>
    </li>
    <li>
      <a class="grey-text text-darken-2" href="#!">
        <i class="material-icons ">access_time</i>Time</a>
    </li>
    <li>
      <a class="grey-text text-darken-2" href="#!">
        <i class="material-icons ">person</i>Yours</a>
    </li>
  </ul>
</div>
<br/>
<% @posts.each do |post| %>
<div class="row card #fafafa hoverable">
  <div class="col m12 center-align">
    <button class="waves-effect waves-green btn-flat left">
      <%= link_to like_post_path(post), method: :put do %>
      <i class="material-icons clear">arrow_upward</i>
      <%= post.get_upvotes.size %>
      <% end %>
    </button>
  </div>
  <div class="col s1 card-content black-text center-align">
    <h1><%= post.get_upvotes.size - post.get_downvotes.size %></h1>
  </div>
  <div class="col s11 card-content black-text">
    <h1 class="title" href="http://<%= post.url %>" target="_blank">
      <%= link_to post.name, post_path(post.id)%>
    </h1>
    <h6 class="grey-text text-darken-3">
      <%= post.description %>
    </h6>
  </div>
  <div class="col m12 center-align">
    <button class="waves-effect waves-red btn-flat left">
      <%= link_to dislike_post_path(post), method: :put do %>
      <i class="material-icons clear">arrow_downward</i>
      <%= post.get_downvotes.size %>
      <% end %>
    </button>
  </div>
  <!-- <%= link_to like_post_path(post), method: :put do %>
    Upvote
    <%= post.get_upvotes.size %>
    <% end %>
    <%= link_to dislike_post_path(post), method: :put do %>
    Downvote
    <%= post.get_downvotes.size %>
    <% end %> -->
</div>
<% end %>
<div class="center-align grey lighten-4">
  <%= link_to "Home", home_path, class:"btn-flat grey-text text-darken-2"%>
</div>