config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  #Home route
  get 'home/index', as: 'home'

  #Users routes
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  post '/users', to: 'users#create'
  patch '/users/:id', to: 'users#update'

  #Sessions routes
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

  #Post routes
  get '/posts', to: 'posts#index', as: 'posts'
  get '/posts/newest', to: 'posts#date_sort', as: 'posts_by_date'
  get '/posts/:id', to: 'posts#show', as: 'post'
  get '/posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  patch '/posts/:id', to: 'posts#update'
  delete '/posts/:id', to: 'posts#destroy'

  #Topics routes
  get '/topics', to: 'topics#index', as: 'topics'
  get '/topics/:id', to: 'topics#show', as: 'topic'
  get '/topic/new', to: 'topics#new', as: 'new_topic'
  get '/topics/:id/edit', to: 'topics#edit', as: 'edit_topic'
  post '/topics', to: 'topics#create', as: 'create_topic'
  patch '/topics/:id', to: 'topics#update'
  delete '/topics/:id', to: 'topics#destroy'

  #topic-post routes
  get '/topics/:id/post/new', to: 'posts#new', as: 'new_post'
  get '/topics/:id/posts', to: 'topics#show'
  post '/topics/:id/posts', to: 'posts#create', as: 'create_post'

  # Voting routes
  resources :posts, only: [] do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end


end

app/models/post.rb
class Post < ApplicationRecord

  acts_as_votable
  validates :name, :description, :url, :content, presence: true


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # has_many :users
  # :current_user
  # user = User.find_by_username(params[:username])
  # if user && user.authenticate(params[:password])

  # can you combine both of these separate functions into one that takes an argument?
  # can you move these out into the models file?

  def index
    @posts = Post.order(cached_votes_up: :desc)
  end

  def date_sort
    @posts = Post.order(created_at: :desc)
  end

  def new
    @post = Post.new
    @current_user = current_user
  end

  def create
    post = Post.new(post_params)
    post[:user_id] = current_user.id
    # post[:topic_id] = params[:id].to_i

    # remove console displays from production code
    puts post.inspect

    if post.save
      redirect_to post_path(post)
    else
      # remove console displays from production code
      puts post.errors.messages
      flash[:notice]=post.errors.messages
      render :new
    end
  end

  def show
    post_id = params[:id]
    @post = Post.find_by_id(post_id)
  end

  def edit
    post_id = params[:id]
    @post = Post.find_by_id(post_id)
  end


  def update
    post_id = params[:id]
    post = Post.find_by_id(post_id)
    post.update_attributes(post_params)
    redirect_to post_path(post_id)
  end

  def destroy
    post_id = params[:id]
    post = Post.find_by_id(post_id)
    post.destroy
    redirect_to posts_path
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    session[:return_to] ||= request.referer
    redirect_to session.delete(:return_to)
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    session[:return_to] ||= request.referer
    redirect_to session.delete(:return_to)
  end

  def set_topic
    @topic = Topic.find_by_id[:topic_id]
  end

  private

  def post_params
    params.require(:post).permit(:name,:description,:url,:content)
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  # def current_topic
  #   @current_topic = Topic.find_by_id()


end

app/views/posts/date_sort.html.erb
<div class="center-align grey lighten-4">
  <%= link_to "Create New Post", new_post_path, class:"btn-flat center grey-text text-darken-2"%>
  <div class="container grey lighten-4">
    <br/>
    <a class='dropdown-button btn-flat white grey-text text-darken-2' href='#' data-activates='dropdown1'>Filter By</a>
  </div>
  <!-- Dropdown Trigger -->
  <!-- Dropdown Structure -->
  <ul id='dropdown1' class='dropdown-content'>
    <li>
      <%= link_to "Votes", posts_path, class:"btn-flat center grey-text text-darken-2"%>
    </li>
    <li>
      <%= link_to "Newest", posts_by_date_path, class:"btn-flat center grey-text text-darken-2"%>
    </li>
  </ul>
</div>
<br/>
<% @posts.each do |post| %>
<div class="row card #fafafa hoverable">
  <div class="col m12 center-align">
    <button class="waves-effect waves-green btn-flat left">
      <%= link_to like_post_path(post), method: :put do %>
      <i class="material-icons clear">arrow_upward</i>
      <%= post.get_upvotes.size %>
      <% end %>
    </button>
  </div>
  <div class="col s1 card-content black-text center-align">
    <h2><%= post.get_upvotes.size - post.get_downvotes.size %></h2>
  </div>
  <div class="col s11 card-content black-text">
    <h2 class="title" href="http://<%= post.url %>" target="_blank">
      <%= link_to post.name, post_path(post.id)%>
    </h2>
    <h6 class="grey-text text-darken-3">
      <%= post.description %>
    </h6>
  </div>
  <div class="col m12 center-align">
    <button class="waves-effect waves-red btn-flat left">
      <%= link_to dislike_post_path(post), method: :put do %>
      <i class="material-icons clear">arrow_downward</i>
      <%= post.get_downvotes.size %>
      <% end %>
    </button>
  </div>
</div>
<% end %>
<div class="center-align grey lighten-4">
  <%= link_to "Home", home_path, class:"btn-flat grey-text text-darken-2"%>
</div>

app/views/posts/edit.html.erb
<% flash.each do |name, msg| %>
<div class="red-text"><%= msg %></div>
<% end %>
<%= form_for @post do |f| %>
<div class="grey lighten-4 z-depth-3">
  <div class="container">
    <h3 class="center-align">Edit Post</h3>
    <div>
      <h5>Name:</h5>
      <%= f.text_field :name %>
      <h5>Description:</h5>
      <%= f.text_field :description %>
      <h5>Link:</h5>
      <%= f.text_field :url %>
      <h5>Content:</h5>
      <%= f.text_area :content, class:"materialize-textarea"%>
    </div>
    <div class="center-align">
      <%= f.submit "Save Post", class:"btn-flat"%>
      <%= link_to "Cancel", post_path(@post.id), class:"btn-flat"%>
      <br />
    </div>
  </div>
</div>
<% end %>

app/views/posts/index.html.erb
<div class="center-align grey lighten-4">
  <%= link_to "Create New Post", new_post_path, class:"btn-flat center grey-text text-darken-2"%>
  <div class="container grey lighten-4">
    <br/>
    <a class='dropdown-button btn-flat white grey-text text-darken-2' href='#' data-activates='dropdown1'>Filter By</a>
  </div>
  <!-- Dropdown Trigger -->
  <!-- Dropdown Structure -->
  <ul id='dropdown1' class='dropdown-content'>
    <li>
      <%= link_to "Votes", posts_path, class:"btn-flat center grey-text text-darken-2"%>
    </li>
    <li>
      <%= link_to "Newest", posts_by_date_path, class:"btn-flat center grey-text text-darken-2"%>
    </li>
  </ul>
</div>
<br/>
<% @posts.each do |post| %>
<div class="row card #fafafa hoverable">
  <div class="col m12 center-align">
    <button class="waves-effect waves-green btn-flat left">
      <%= link_to like_post_path(post), method: :put do %>
      <i class="material-icons clear">arrow_upward</i>
      <%= post.get_upvotes.size %>
      <% end %>
    </button>
  </div>
  <div class="col s1 card-content black-text center-align">
    <h2><%= post.get_upvotes.size - post.get_downvotes.size %></h2>
  </div>
  <div class="col s11 card-content black-text">
    <h2 class="title" href="http://<%= post.url %>" target="_blank">
      <%= link_to post.name, post_path(post.id)%>
    </h2>
    <h6 class="grey-text text-darken-3">
      <%= post.description %>
    </h6>
  </div>
  <div class="col m12 center-align">
    <button class="waves-effect waves-red btn-flat left">
      <%= link_to dislike_post_path(post), method: :put do %>
      <i class="material-icons clear">arrow_downward</i>
      <%= post.get_downvotes.size %>
      <% end %>
    </button>
  </div>
</div>
<% end %>
<div class="center-align grey lighten-4">
  <%= link_to "Home", home_path, class:"btn-flat grey-text text-darken-2"%>
</div>

app/views/posts/new.html.erb
<% flash.each do |name, msg| %>
<div class="red-text"><%= msg %></div>
<% end %>
<%= yield %>
<%= form_for :post, url: "/topics/:id/posts", method: "post" do |f| %>
<div class="grey lighten-4 z-depth-3">
  <div class="container">
    <h3 class="center-align">Create New Post</h3>
    <h5>Name:</h5>
    <%= f.text_field :name %>
    <h5>Description:</h5>
    <%= f.text_field :description %>
    <h5>Link:</h5>
    <%= f.text_field :url %>
    <% f.number_field :topic_id, :value => params[:id].to_i%>
    <h5>Content:</h5>
    <%= f.text_area :content, class:"materialize-textarea"%>
    <div class="center-align">
      <%= f.submit "Submit", class:"btn-flat"%>
      <br>
    </div>
  </div>
</div>
<% end %>
<%= console %>

app/views/posts/show.html.erb
<div class="row grey lighten-4 z-depth-3">
    <div class="grey lighten-4">
      <h3 class="center container">
        <br /><%= @post.name %><br />
        <%= link_to "Edit Post", edit_post_path(@post.id), class:"btn-flat"%>
        <%= link_to "Delete", @post, method: :delete, class:"btn-flat"%>
      </h3>
      <div class="container">
        <h5><%= @post.description %></h5>
        <h5>
          <a href="http://<%= @post.url %>"><%= @post.url%></a>
        </h5>
        <div class="white">
          <p><%= markdown(@post.content) %></p>
        </div>
      </div>
  </div>
  <div class="center-align grey lighten-4 container">
    <%= link_to "Back", posts_path, class:"btn-flat"%>
  </div>
</div>